export class Product {
    constructor(
        public id?: number,
        public maintag?: number,
        public mainCategory?: number,
        public category?: number,
        public subCategory?: number,
        public productName?: string,
        public brandName?: string,
        public manufacturerName?: string,
        public productCode?: string,
        public productSRNumber?: string,
        public productPrice?: number,
        public productPer?: number,
        public discountPrice?: number,
        public quantity?: number,
        public soldQuantity?: number,
        public size?: string,
        public color?: string,
        public descripition?: string,
        public productDimension?: string,
        public itemWeight?: string,
        public taxslab?: string,
        public emiOptions?: boolean,
        public avibilityStatus?: boolean,
        public relatedProduct?: boolean,
        public isNewArrival?: boolean,
        public isBestProduct?: boolean,
        public isHot?: boolean,
        public isOnSale?: boolean,
        public startRating?: boolean,
        public isActive?: number,
        public createddate?: Date,
        public updateddate?: Date,
        public productImages?: any[],

        // public productQuantity?: number [],
        //public selectedSize?: string [],
        // public productListImage?: string,
        public sizeList?: any[],
        public productMainImage?: any[],
        public selectedSize?: any[],
        public multi?: any[],
        public selectedCheck?: Boolean,
        public index?: number,
    ) {
    }
}